
export default {
    ambiente: require("@/assets/icons/ambiente.png"),
    saude: require("@/assets/icons/saude.png"),
    solPessoa: require("@/assets/icons/solPessoa.png"),
    capiCoin: require("@/assets/icons/capiCoin.png"),
    arrowRed: require("@/assets/icons/arrowRed.png"),
    arrowGreen: require("@/assets/icons/arrowGreen.png"),
    arrowOrange: require("@/assets/icons/arrowOrange.png"),
    crianca: require("@/assets/icons/crianca.png"),
    empresa: require("@/assets/icons/empresa.png"),
    geral: require("@/assets/icons/geral.png"),
    jovem: require("@/assets/icons/jovem.png"),
    idoso: require("@/assets/icons/idoso.png"),
    mulher: require("@/assets/icons/mulher.png"),
    pcd: require("@/assets/icons/pcd.png"),
    pet: require("@/assets/icons/pet.png"),
    servidor: require("@/assets/icons/servidor.png"),
    turista: require("@/assets/icons/turista.png"),
    eye: require("@/assets/icons/eye.png"),
    eyeSlash: require("@/assets/icons/eyeSlash.png"),
    shinyCoin: require("@/assets/icons/shinyCoin.png"),
    logoConecta: require("@/assets/images/logoConecta.png"),
    wave: require("@/assets/images/wave.png"),
    crown: require("@/assets/icons/crown.png"),
    back: require("@/assets/icons/backArrow.png"),
    check: require("@/assets/icons/check.png"),
    arrowWhite: require("@/assets/icons/arrowWhite.png"),
  };
  